name: Publish 

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: ğŸ§° Install Dependencies (Base, Solver)
        run: pacman -Syu --noconfirm git emscripten cmake ninja nodejs pnpm

      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ¦¥ Cache Solver
        uses: actions/cache@v4
        with:
          key: solver-build 
          path: |
            solver/build

      - name: ğŸ”¨ Build Solver 
        run: |
          cd solver
          /usr/lib/emscripten/emcmake cmake -B build -G Ninja
          cmake --build build -j$(nproc)

      - name: ğŸš§ Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: ğŸ“„ Setup Pages
        uses: actions/configure-pages@v4

      - name: ğŸ§° Install Dependencies (Frontend)
        run: "pnpm i"

      - name: ğŸ—ï¸ Build Frontend
        run: "pnpm run build" 

      - name: ğŸ“¤ Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: âš™ï¸ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
